# Generated by Django 6.0.1 on 2026-01-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestionOption',
        ),
    ]
