# Generated by Django 6.0.1 on 2026-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0003_delete_quizquestionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
